### ISSUE TITLE
display user history is not working

### ISSUE THREAD

**Issue by paradite** [kanghj/fyp-chrome-extension#4]
I tried to load the learning history page for users on Android, but the page shows some error message instead:

http://wordnews.herokuapp.com/displayHistory?name=fc644fc1da2c183d

(or this?)
http://wordnews-mobile.herokuapp.com/displayHistory?name=fc644fc1da2c183d

`fc644fc1da2c183d` is the android ID

Same issue for any arbitrary user id:
http://wordnews.herokuapp.com/displayHistory?name=id12

Can you check?

Update:
After a few hours(minutes?), the url seems to load, but the content is empty although I did click on some words using the account ID.

Screenshot: 

![screenshot_20160710-133419](https://cloud.githubusercontent.com/assets/1209810/16711863/58c4de8c-46a3-11e6-988e-8e4932abc105.png)

**Comment by kanghj** [comment]
Hi Zhu Liang,

It should be partially fixed now, can you try again? 

Edit: 
anyway, to elaborate, just as you deduced, the error is just because the user account doesn't exist yet. The old workflow using the Chrome extension always assumed a standard workflow where the user is forced to edit the settings of the extension first before he can use the translation feature or see his history. This was done early in the project's history, and I have never really tried to fix it.

Btw, I turned off that error page (with detailed error details and trace), let me (or Tao) know if it's more helpful to be able to see the error messages and I can switch it back.

**Comment by paradite** [comment]
@kanghj 
I clicked several words on my Android device using the account ID`fc644fc1da2c183d`.
But the page still displays empty lists, is that normal?

**Comment by kanghj** [comment]
@paradite, hmm, something must be wrong with the code to send to `/remember` then. Are you using the correct user id? The learning history is working for me.

**Comment by kanghj** [comment]
Anyway, will you be posting your source code online?

**Comment by paradite** [comment]
@kanghj I've added you to the repo.

I didn't modify the js file for sending the user's behavior, the only thing I changed was the user's ID, which I get from Android client.

Do you have some server log or database viewer to verify the records?

**Comment by kanghj** [comment]
Yes @paradite, I use the Papertrail addon on Heroku, you should be able to access it too. From the server logs, the user id `fc644fc1da2c183d` is only used on `displayHistory`.

**Comment by paradite** [comment]
Okay, I will check the logs.

**Comment by paradite** [comment]
Btw, which server is the actual server? 
http://wordnews.herokuapp.com

or this?
http://wordnews-mobile.herokuapp.com

**Comment by kanghj** [comment]
When I was doing some work on the backend, there was a version of WordNews that was already made public in the Chrome Webstore, so the public version used wordnews.herokuapp.com while I worked on wordnews-mobile.herokuapp.com. Currently, there is no difference between the two anymore. 

Edit: I mean there's no code difference between the two, but the public Chrome Extension is using wordnews.herokuapp.com while wordnews-mobile.herokuapp.com should be unused.

**Comment by kanghj** [comment]
Ok, so that should fix the bug then. Closing this
